import '@/styles/globals.css';
import type { Metadata } from 'next';
import ConfigureAmplifyClientSide from './amplify-cognito-config';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className='flex justify-center items-center h-screen'>
      <ConfigureAmplifyClientSide />
      {children}
    </div>
  );
}
