/* tslint:disable */
/* eslint-disable */
/**
 * Order API
 * Use this API to handle create orders from frontend 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
    Order
} from '../models';
import {
    OrderToJSON
} from '../models';
import * as runtime from '../runtime';

export interface CreateOrderRequest {
    order?: Order;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     * Create an order
     * createOrder
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderToJSON(requestParameters.order),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create an order
     * createOrder
     */
    async createOrder(requestParameters: CreateOrderRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrderRaw(requestParameters, initOverrides);
    }

}
