name: Backend Install

description: 'Installs required dependencies for backend'

runs:
  using: composite

  steps:
    - name: 🔒 Cache CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v3
      with:
        path: infrastructure/node_modules
        key: infrastructure-${{ hashFiles('infrastructure/package-lock.json') }}

    - name: 📥 Install CDK
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: infrastructure
      shell: bash

    - name: 📥 Install Backend
      run: npm run cinstall-backend
      working-directory: infrastructure
      shell: bash
