name: Infrastructure Install

description: 'Installs required dependencies for infrastructure'

runs:
  using: composite

  steps:
    - name: 🔒 Cache CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v4
      with:
        path: infrastructure/node_modules
        key: infrastructure-${{ hashFiles('infrastructure/package-lock.json') }}

    - name: 📥 Install CDK Dependencies
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: infrastructure
      shell: bash

    - name: 📥 Install Backend Dependencies
      run: |
        # Install Lambda dependencies
        find ./lambda -mindepth 2 -maxdepth 2 -type f -name 'package.json' |
        while IFS= read -r file; do
          echo "💾 Installing dependencies for $file"
          cd "$(dirname "$file")"
          npm ci
          cd - >/dev/null
        done
      working-directory: backend
      shell: bash
