/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthAccountsIndexRouteImport } from './routes/_auth/accounts/index'
import { Route as AuthAccountsAccountIdRouteImport } from './routes/_auth/accounts/$accountId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsIndexRoute = AuthAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsAccountIdRoute = AuthAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/accounts/': typeof AuthAccountsIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/accounts': typeof AuthAccountsIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/_auth/accounts/': typeof AuthAccountsIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$accountId'
    | '/accounts/'
    | '/dashboard/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/$accountId'
    | '/accounts'
    | '/dashboard'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/accounts/$accountId'
    | '/_auth/accounts/'
    | '/_auth/dashboard/'
    | '/_auth/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts/': {
      id: '/_auth/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthAccountsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts/$accountId': {
      id: '/_auth/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthAccountsAccountIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountsAccountIdRoute: typeof AuthAccountsAccountIdRoute
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountsAccountIdRoute: AuthAccountsAccountIdRoute,
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
