/* tslint:disable */
/* eslint-disable */
/**
 * Order API
 * Use this API to handle create orders from frontend 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryAddress
 */
export interface DeliveryAddress {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof DeliveryAddress
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryAddress
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryAddress
     */
    address?: string;
}

/**
 * Check if a given object implements the DeliveryAddress interface.
 */
export function instanceOfDeliveryAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeliveryAddressFromJSON(json: any): DeliveryAddress {
    return DeliveryAddressFromJSONTyped(json, false);
}

export function DeliveryAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function DeliveryAddressToJSON(value?: DeliveryAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'full_name': value.fullName,
        'phone_number': value.phoneNumber,
        'address': value.address,
    };
}

