name: Frontend Install

description: 'Installs required dependencies for frontend'

runs:
  using: composite

  steps:
    - name: 🔒 Cache CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v4
      with:
        path: infrastructure/node_modules
        key: infrastructure-${{ hashFiles('infrastructure/package-lock.json') }}

    - name: 📥 Install CDK
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: infrastructure
      shell: bash

    - name: 🔒 Cache Frontend
      id: frontend-cache
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: frontend-${{ hashFiles('frontend/package-lock.json') }}

    - name: 📥 Install Frontend
      if: steps.frontend-cache.outputs.cache-hit != 'true'
      run: |
        echo "💾 Installing dependencies for ../frontend/package.json"
        npm ci --prefix ../frontend --include=optional
        echo "🔧 Rebuilding native modules"
        npm rebuild --prefix ../frontend lightningcss 2>/dev/null || true
      working-directory: backend
      shell: bash

    - name: 🏗  Generate Convex API
      run: |
        cd ../frontend
        npx convex codegen
      env:
        CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
      working-directory: backend
      shell: bash
