name: build

on: [pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/client
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM Dependencies (Backend)
        run: npm ci
        working-directory: backend

      - name: Build Backend
        run: npm run build
        working-directory: backend

      - name: Install NPM Dependencies (Client)
        run: npm ci
        working-directory: client

      - name: Build Client
        run: npm run build:prod
        working-directory: client

      - name: Run CDK Unit Tests
        run: npm run test
        working-directory: backend
