name: Build and Test
on: [pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/spa
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CDK packages
        run: |
          cd ../cdk
          npm ci
          cd ../spa
      - name: Run CDK Unit Tests
        run: |
          npm build
          cd ../cdk
          npm run test
